# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 650)
        Form.setStyleSheet("#Form{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.basla = QtWidgets.QPushButton(Form)
        self.basla.setGeometry(QtCore.QRect(120, 500, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(38)
        self.basla.setFont(font)
        self.basla.setObjectName("basla")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 40, 461, 351))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.saniye = QtWidgets.QLineEdit(self.groupBox)
        self.saniye.setGeometry(QtCore.QRect(100, 260, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.saniye.setFont(font)
        self.saniye.setObjectName("saniye")
        self.deqiqe = QtWidgets.QLineEdit(self.groupBox)
        self.deqiqe.setGeometry(QtCore.QRect(100, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deqiqe.setFont(font)
        self.deqiqe.setObjectName("deqiqe")
        self.saat = QtWidgets.QLineEdit(self.groupBox)
        self.saat.setGeometry(QtCore.QRect(100, 60, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.saat.setFont(font)
        self.saat.setText("")
        self.saat.setObjectName("saat")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(180, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 420, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(170, 170, 255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.basla.setText(_translate("Form", "BAŞLA"))
        self.label.setText(_translate("Form", "SAAT"))
        self.label_2.setText(_translate("Form", "DƏQİQƏ"))
        self.label_3.setText(_translate("Form", "SANİYƏ"))
        self.label_4.setText(_translate("Form", "00:00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
